### ISSUE TITLE
将博客迁移到又拍云

### ISSUE THREAD

**Issue by her-cat** [her-cat/blog-comment#40]
https://her-cat.com/posts/2023/01/31/blog-migration-to-upyun/ 

 考虑到使用一台独立的服务器来部署静态博客多少有点浪费，所以决定将博客迁移到又拍云上，一是可以节省服务器成本；二是可以利用又拍云多节点 CDN 提升博客的访问速

**Comment by koobai** [comment]
你好， 利用 Github Actions 自动同步到又拍云上的yml文件不知道能不能分享下，感谢～

**Comment by her-cat** [comment]
> @koobai
> 你好， 利用 Github Actions 自动同步到又拍云上的yml文件不知道能不能分享下，感谢～

以下是我的 yml 文件：

```yml
# workflow name
name: Deploy Upyun CI

on:
  push:
    branches:
      - hugo

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # check it to your workflow can access it
      # from: https://github.com/actions/checkout
      - name: Checkout Repository master branch
        uses: actions/checkout@master

      # from: https://github.com/actions/setup-node
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.101.0'

      - name: Build static files
        run: hugo --minify --environment production

      - name: Set up Go
        uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.17

      - name: Build deployer
        run: cd ./.github/upyun-deployer && go build .

      - name: Deploy
        env:
          UPYUN_SERVICE_NAME: ${{ secrets.UPYUN_SERVICE_NAME }}
          UPYUN_OPERATOR_NAME: ${{ secrets.UPYUN_OPERATOR_NAME }}
          UPYUN_OPERATOR_PWD: ${{ secrets.UPYUN_OPERATOR_PWD }}
        run: ./.github/upyun-deployer/upyun-deployer -bucket ${UPYUN_SERVICE_NAME} -operator ${UPYUN_OPERATOR_NAME} -password ${UPYUN_OPERATOR_PWD} -dir public
```

上面的 ./.github/upyun-deployer 就是文中提到的部署脚本。

**Comment by koobai** [comment]
非常感谢提供，不知道能不能同时提供下你写的部署脚本，原文中没找到，感谢。
网上找了到相关可以同步到又拍云的，但不是增量更新、且github删除了相关文件，远端也没删除。看到你博文中都提到这些，不知道能不能分享下./.github/upyun-deployer 脚本，再次感谢

**Comment by her-cat** [comment]
> @koobai
> 非常感谢提供，不知道能不能同时提供下你写的部署脚本，原文中没找到，感谢。
> 网上找了到相关可以同步到又拍云的，但不是增量更新、且github删除了相关文件，远端也没删除。看到你博文中都提到这些，不知道能不能分享下./.github/upyun-deployer 脚本，再次感谢

可以的，我晚点整理一下代码，提交到 GitHub 之后我会在评论区回复你。

**Comment by koobai** [comment]
太感谢了，为了又拍云找了很久相关工作流。
发现你博文写的很清楚，抱着试试看问下，感谢感谢～

**Comment by koobai** [comment]
弱弱问下，大概什么时候能整理好么，哈哈～感谢

**Comment by her-cat** [comment]
> @koobai
> 弱弱问下，大概什么时候能整理好么，哈哈～感谢

代码库：https://github.com/her-cat/upyun-deployer

你可以直接把代码 clone 到你的仓库的 .github 目录下，然后使用昨天我提供的 yml 文件就可以使用了。
有任何问题欢迎联系我。

PS: 我正在尝试将它打包成一个 Github  Actions，这样就只需要修改 yml 配置文件，不需要再 clone 代码了，预计这两天可以完成。

**Comment by koobai** [comment]
太感谢了，先用起来。然后再等你这两天打包，之后再更新。
再次感谢～

**Comment by koobai** [comment]
已运行成功，不过有个问题，如果是.svg格式的，同步之后又拍云里显示的文件类型为text/plain; charset=utf-8，这样就导致svg格式无效了

**Comment by koobai** [comment]
<img width="1143" alt="image" src="https://github.com/her-cat/blog-comment/assets/50470569/cd3e2be8-ea36-41a6-9efc-52083f66ba1f">
正常应该是蓝色这样显示，红色就会导致无法显示了

**Comment by her-cat** [comment]
> @koobai
> <img width="1143" alt="image" src="https://github.com/her-cat/blog-comment/assets/50470569/cd3e2be8-ea36-41a6-9efc-52083f66ba1f">
> 正常应该是蓝色这样显示，红色就会导致无法显示了

我修改了检测文件类型的逻辑，你更新一下代码看看。

**Comment by koobai** [comment]
已正常，完美～感谢感谢

**Comment by her-cat** [comment]
> @koobai
> 已正常，完美～感谢感谢

😄😄😄

**Comment by koobai** [comment]
也是自己玩玩博客koobai.com，先是通过类似于PicGo图片工具传文件到github然后通过github自动传到各存储桶，这下方便了，再次感谢。
然后就等你后期直接集成Github Actions，到时更新下yml就可以，哈哈～完美

**Comment by her-cat** [comment]
> @koobai
> 也是自己玩玩博客koobai.com，先是通过类似于PicGo图片工具传文件到github然后通过github自动传到各存储桶，这下方便了，再次感谢。
> 然后就等你后期直接集成Github Actions，到时更新下yml就可以，哈哈～完美

你的博客很不错！我也在考虑记录一些生活相关的东西，一直没动手😂

**Comment by koobai** [comment]
搞起来，折腾的乐趣就在于不停的折腾，哈哈哈

**Comment by her-cat** [comment]
> @koobai
> 也是自己玩玩博客koobai.com，先是通过类似于PicGo图片工具传文件到github然后通过github自动传到各存储桶，这下方便了，再次感谢。
> 然后就等你后期直接集成Github Actions，到时更新下yml就可以，哈哈～完美

哈喽，已经打包成 Github Action 了，可以参考 README 中的使用示例修改 yml 文件。

https://github.com/her-cat/upyun-deployer

**Comment by koobai** [comment]
哇哦，效率。
已替换，并成功运行，完美，舒坦了，大大的点赞👍

**Comment by her-cat** [comment]
> @koobai
> 哇哦，效率。
> 已替换，并成功运行，完美，舒坦了，大大的点赞👍

哈哈，也感谢你的使用。

**Comment by koobai** [comment]
发了篇博文，记录备忘下，省得以后又给忘了😂
已经成功安利两位博友使用～
https://koobai.com/blogimg/

也再次感谢，解决了自己一大难题。

**Comment by dongyubin** [comment]
你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`

希望解答，在此感谢

**Comment by her-cat** [comment]
> @dongyubin
> 你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`
> 
> 希望解答，在此感谢

现在只支持上传到又拍云的根目录下，不支持上传到指定的目录下。我等会增加一个目标目录的参数以支持这个功能。

**Comment by her-cat** [comment]
> @dongyubin
> 你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`
> 
> 希望解答，在此感谢

如果你想要将仓库根目录上传到又拍云的话，只需要将 dir 指定为空或者不设置该参数即可。

**Comment by dongyubin** [comment]
> @her-cat
> > @dongyubin
> > 你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`
> > 
> > 希望解答，在此感谢
> 
> 现在只支持上传到又拍云的根目录下，不支持上传到指定的目录下。我等会增加一个目标目录的参数以支持这个功能。
> 

感谢，辛苦了

**Comment by her-cat** [comment]
> @dongyubin
> > @her-cat
> > > @dongyubin
> > > 你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`
> > > 
> > > 希望解答，在此感谢
> > 
> > 现在只支持上传到又拍云的根目录下，不支持上传到指定的目录下。我等会增加一个目标目录的参数以支持这个功能。
> > 
> 
> 感谢，辛苦了

已经支持上传到指定的目录了。需要注意的是版本由 v1 变成了 v1.0.1，增加了 publish_dir 参数，详细说明请参考说明文档。

https://github.com/her-cat/upyun-deployer#example-usage

**Comment by her-cat** [comment]
> @dongyubin
> 你好，我用了 https://github.com/her-cat/upyun-deployer，我想要将 https://github.com/dongyubin/WP-CDN-02这个仓库，上传到又拍云下的 WP-CDN-02 文件夹下，我该如何设置参数？现在我设置的dir是`./`上传到的是` /github/workspace/`
> 
> 希望解答，在此感谢

按照你的需求，只要将 publish_dir 设置为 WP-CDN-02 即可：

```yml
      - name: Deploy
        uses: her-cat/upyun-deployer@v1.0.1
        with:
          bucket: ${{ secrets.UPYUN_BUCKET }}
          operator: ${{ secrets.UPYUN_OPERATOR_NAME }}
          password: ${{ secrets.UPYUN_OPERATOR_PWD }}
          publish_dir: 'WP-CDN-02'
```
